apiVersion: telemetry.openstack.org/v1beta1
kind: Ceilometer
metadata:
  name: ceilometer
  namespace: openstack
spec:
  secret: osp-secret
  centralImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
  notificationImage: quay.io/podified-antelope-centos9/openstack-ceilometer-notification:current-podified
  sgCoreImage: quay.io/infrawatch/sg-core:v5.2.0-nextgen
  computeImage: quay.io/podified-antelope-centos9/openstack-ceilometer-compute:current-podified
  ipmiImage: quay.io/podified-antelope-centos9/openstack-ceilometer-ipmi:current-podified
  nodeExporterImage: quay.io/prometheus/node-exporter:v1.5.0
